### ISSUE TITLE
You left a grab in there

### ISSUE THREAD

**Issue by fuzzlesfixer** [KSCH-58/sub#2]
Delete it and prob the repo aswell because it might have stuff on it. I’m not check8ng

**Comment by KSCH-58** [comment]
no there isn't any grabber in it

**Comment by fuzzlesfixer** [comment]
I mean u left a gofile

**Comment by fuzzlesfixer** [comment]
Delete it before anyone downloads.

**Comment by fuzzlesfixer** [comment]
I would delete repo so they can’t see commit history
